name: SonarQube Build

on:
  push:
    branches:
      - "*"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Compile
        run: mvn --batch-mode --update-snapshots compile

      - name: Check if files have been modified and fail if so
        run: |
          git diff --exit-code
          if [ $? -ne 0 ]; then
            echo "Files have been modified by the build process. Please run 'mvn compile' locally and commit the changes."
            exit 1
          fi
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=PS5-Takenoko
